// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Utiliser la variable d'environnement ou une valeur par défaut pour le build
const databaseUrl = process.env.POSTGRES_PRISMA_URL || 
                     process.env.DATABASE_URL || 
                     "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
